#!/usr/bin/env bash
set -euo pipefail

# Deploy contracts to local Anvil node
# Usage: ./scripts/deploy-local.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$PROJECT_ROOT/contracts"

# Default anvil private key (account 0)
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
RPC_URL="http://127.0.0.1:8545"

echo "=== EduChain 智慧教育系统 - Local Deployment ==="
echo ""

# Check if anvil is running
if ! cast chain-id --rpc-url "$RPC_URL" &>/dev/null; then
    echo "Starting anvil..."
    anvil --block-time 2 &
    ANVIL_PID=$!
    sleep 2
    echo "Anvil started (PID: $ANVIL_PID)"
else
    echo "Anvil already running on $RPC_URL"
fi

echo ""
echo "Deploying contracts..."
cd "$CONTRACTS_DIR"

# Run forge script deployment
forge script script/Deploy.s.sol:Deploy \
    --rpc-url "$RPC_URL" \
    --private-key "$DEPLOYER_KEY" \
    --broadcast \
    -vvv

echo ""
echo "=== Deployment Complete ==="
echo ""

# Extract deployed addresses from broadcast
BROADCAST_FILE="$CONTRACTS_DIR/broadcast/Deploy.s.sol/31337/run-latest.json"
if [ -f "$BROADCAST_FILE" ]; then
    echo "Deployed addresses:"
    echo "---"
    # Parse addresses from broadcast JSON
    REGISTRY=$(cat "$BROADCAST_FILE" | python3 -c "
import json, sys
data = json.load(sys.stdin)
txs = data.get('transactions', [])
for tx in txs:
    if tx.get('contractName') == 'Registry':
        print(tx['contractAddress'])
        break
")
    DISPUTE=$(cat "$BROADCAST_FILE" | python3 -c "
import json, sys
data = json.load(sys.stdin)
txs = data.get('transactions', [])
for tx in txs:
    if tx.get('contractName') == 'DisputeResolution':
        print(tx['contractAddress'])
        break
")
    ARBITRATION=$(cat "$BROADCAST_FILE" | python3 -c "
import json, sys
data = json.load(sys.stdin)
txs = data.get('transactions', [])
for tx in txs:
    if tx.get('contractName') == 'ArbitrationCommittee':
        print(tx['contractAddress'])
        break
")
    ORACLE=$(cat "$BROADCAST_FILE" | python3 -c "
import json, sys
data = json.load(sys.stdin)
txs = data.get('transactions', [])
for tx in txs:
    if tx.get('contractName') == 'StakeOracle':
        print(tx['contractAddress'])
        break
")

    echo "  Registry:            $REGISTRY"
    echo "  DisputeResolution:   $DISPUTE"
    echo "  ArbitrationCommittee: $ARBITRATION"
    echo "  StakeOracle:         $ORACLE"
    echo ""

    # Write addresses to frontend config
    ADDRESSES_FILE="$PROJECT_ROOT/frontend/src/contracts/addresses.ts"
    mkdir -p "$(dirname "$ADDRESSES_FILE")"
    cat > "$ADDRESSES_FILE" << EOF
// Auto-generated by deploy-local.sh
// Chain ID: 31337 (Anvil local)

export const CHAIN_ID = 31337;

export const ADDRESSES: Record<number, {
  registry: string;
  disputeResolution: string;
  arbitrationCommittee: string;
  stakeOracle: string;
}> = {
  31337: {
    registry: "${REGISTRY}",
    disputeResolution: "${DISPUTE}",
    arbitrationCommittee: "${ARBITRATION}",
    stakeOracle: "${ORACLE}",
  },
};

export function getAddresses(chainId: number) {
  const addrs = ADDRESSES[chainId];
  if (!addrs) {
    throw new Error(\`No contract addresses configured for chain \${chainId}\`);
  }
  return addrs;
}

export type ContractName = keyof (typeof ADDRESSES)[typeof CHAIN_ID];
EOF
    echo "Addresses written to: $ADDRESSES_FILE"
else
    echo "Warning: Broadcast file not found at $BROADCAST_FILE"
    echo "You may need to manually update frontend/src/contracts/addresses.ts"
fi
